sudo cconv -f UTF8-CN -t UTF8-HK //odoo/custom/auto_backup/i18n/._zh_CN.po -o //odoo/custom/auto_backup/i18n/._zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/custom/auto_backup/i18n/zh_CN.po -o //odoo/custom/auto_backup/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/web_grid/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/web_grid/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/web_gantt/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/web_gantt/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/sale_subscription_asset/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/sale_subscription_asset/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/helpdesk_timesheet/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/helpdesk_timesheet/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_batch_deposit/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_batch_deposit/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/sale_ebay/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/sale_ebay/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/timesheet_grid_sale/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/timesheet_grid_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/delivery_usps/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/delivery_usps/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/event_barcode_mobile/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/event_barcode_mobile/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mrp_workorder/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mrp_workorder/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/marketing_automation/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/marketing_automation/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mass_mailing_themes/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mass_mailing_themes/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/delivery_dhl/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/delivery_dhl/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/delivery_bpost/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/delivery_bpost/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/sale_subscription/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/sale_subscription/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_taxcloud/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_taxcloud/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/project_forecast/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/project_forecast/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_helpdesk_livechat/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_helpdesk_livechat/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/stock_barcode_mobile/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/stock_barcode_mobile/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_sepa_direct_debit/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_sepa_direct_debit/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/sale_account_taxcloud/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/sale_account_taxcloud/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/project_timesheet_forecast_sale/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/project_timesheet_forecast_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/event_barcode/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/event_barcode/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/pos_loyalty/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/pos_loyalty/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_plaid/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_plaid/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_online_sync/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_online_sync/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_bank_statement_import_qif/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_bank_statement_import_qif/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/web_studio/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/web_studio/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/quality_mrp/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/quality_mrp/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_helpdesk_forum/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_helpdesk_forum/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_accountant/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_accountant/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_calendar/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_calendar/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/project_forecast_sale/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/project_forecast_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/web_enterprise/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/web_enterprise/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/delivery_fedex/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/delivery_fedex/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mrp_mps/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mrp_mps/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/web_mobile/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/web_mobile/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_sepa/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_sepa/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_sale_coupon/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_sale_coupon/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/voip_onsip/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/voip_onsip/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/voip/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/voip/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/currency_rate_live/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/currency_rate_live/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_version/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_version/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_bank_statement_import_csv/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_bank_statement_import_csv/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/project_timesheet_synchro/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/project_timesheet_synchro/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_sign/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_sign/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_crm_score/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_crm_score/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_helpdesk_form/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_helpdesk_form/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_studio/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_studio/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_enterprise/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_enterprise/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_helpdesk_slides/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_helpdesk_slides/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_helpdesk/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_helpdesk/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/helpdesk_sale_timesheet/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/helpdesk_sale_timesheet/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/delivery_barcode/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/delivery_barcode/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/hr_expense_sepa/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/hr_expense_sepa/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/delivery_ups/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/delivery_ups/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/base_automation_hr_contract/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/base_automation_hr_contract/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/print/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/print/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/hr_holidays_gantt/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/hr_holidays_gantt/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_delivery_ups/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_delivery_ups/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/l10n_be_coda/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/l10n_be_coda/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/sale_coupon_delivery/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/sale_coupon_delivery/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/hr_appraisal/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/hr_appraisal/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_sale_account_taxcloud/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_sale_account_taxcloud/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mrp_account/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mrp_account/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/l10n_us_check_printing/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/l10n_us_check_printing/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mrp_maintenance/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mrp_maintenance/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_reports_followup/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_reports_followup/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/hr_contract_salary/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/hr_contract_salary/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_form_editor/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_form_editor/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/stock_barcode/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/stock_barcode/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_quote_subscription/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_quote_subscription/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/inter_company_rules/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/inter_company_rules/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/helpdesk/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/helpdesk/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mail_push/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mail_push/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_deferred_revenue/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_deferred_revenue/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/l10n_be_reports/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/l10n_be_reports/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/timesheet_grid/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/timesheet_grid/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/sale_subscription_dashboard/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/sale_subscription_dashboard/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/print_sale/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/print_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_bank_statement_import_camt/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_bank_statement_import_camt/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_3way_match/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_3way_match/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mail_github/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mail_github/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_reports/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_reports/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_yodlee/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_yodlee/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/sale_coupon/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/sale_coupon/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/print_docsaway/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/print_docsaway/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/quality/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/quality/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_bank_statement_import_ofx/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_bank_statement_import_ofx/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mrp_plm/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mrp_plm/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_service_rating/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_service_rating/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_multilang/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_multilang/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/rating_project/i18n/zh_CN.po -o //odoo/odoo-server/addons/rating_project/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/utm/i18n/zh_CN.po -o //odoo/odoo-server/addons/utm/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/mass_mailing_event_track/i18n/zh_CN.po -o //odoo/odoo-server/addons/mass_mailing_event_track/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/mrp_repair/i18n/zh_CN.po -o //odoo/odoo-server/addons/mrp_repair/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_uy/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_uy/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/report_intrastat/i18n/zh_CN.po -o //odoo/odoo-server/addons/report_intrastat/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/maintenance/i18n/zh_CN.po -o //odoo/odoo-server/addons/maintenance/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/web_planner/i18n/zh_CN.po -o //odoo/odoo-server/addons/web_planner/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/im_livechat/i18n/zh_CN.po -o //odoo/odoo-server/addons/im_livechat/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_ar/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_ar/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_in_hr_payroll/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_in_hr_payroll/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_cancel/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_cancel/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/mrp_byproduct/i18n/zh_CN.po -o //odoo/odoo-server/addons/mrp_byproduct/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/web_kanban_gauge/i18n/zh_CN.po -o //odoo/odoo-server/addons/web_kanban_gauge/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale_management/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale_management/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_address_city/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_address_city/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account/i18n/zh_CN.po -o //odoo/odoo-server/addons/account/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_analytic_default/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_analytic_default/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sales_team/i18n/zh_CN.po -o //odoo/odoo-server/addons/sales_team/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_test/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_test/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_at/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_at/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/mail/i18n/zh_CN.po -o //odoo/odoo-server/addons/mail/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/google_account/i18n/zh_CN.po -o //odoo/odoo-server/addons/google_account/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_order_dates/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_order_dates/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_rating_project/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_rating_project/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_form/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_form/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_expense/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_expense/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_customer/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_customer/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_lu/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_lu/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_bank_statement_import/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_bank_statement_import/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_import_module/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_import_module/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/product_extended/i18n/zh_CN.po -o //odoo/odoo-server/addons/product_extended/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_sg/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_sg/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_livechat/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_livechat/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_syscohada/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_syscohada/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/lunch/i18n/zh_CN.po -o //odoo/odoo-server/addons/lunch/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_crm/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_crm/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_payment/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_payment/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_hr_recruitment/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_hr_recruitment/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_transfer/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_transfer/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_quote/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_quote/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_stock/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_stock/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_expense_check/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_expense_check/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_geolocalize/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_geolocalize/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/contacts/i18n/zh_CN.po -o //odoo/odoo-server/addons/contacts/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_crm/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_crm/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/product_expiry/i18n/zh_CN.po -o //odoo/odoo-server/addons/product_expiry/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_th/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_th/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/auth_crypt/i18n/zh_CN.po -o //odoo/odoo-server/addons/auth_crypt/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/mrp/i18n/zh_CN.po -o //odoo/odoo-server/addons/mrp/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/survey_crm/i18n/zh_CN.po -o //odoo/odoo-server/addons/survey_crm/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_payroll/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_payroll/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/gamification/i18n/zh_CN.po -o //odoo/odoo-server/addons/gamification/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale_wishlist/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale_wishlist/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_invoicing/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_invoicing/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_forum/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_forum/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_slides/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_slides/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/google_spreadsheet/i18n/zh_CN.po -o //odoo/odoo-server/addons/google_spreadsheet/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/project_timesheet_holidays/i18n/zh_CN.po -o //odoo/odoo-server/addons/project_timesheet_holidays/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_eu_service/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_eu_service/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_timesheet/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_timesheet/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_gt/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_gt/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_forum_doc/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_forum_doc/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_vat_autocomplete/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_vat_autocomplete/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/mass_mailing/i18n/zh_CN.po -o //odoo/odoo-server/addons/mass_mailing/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_attendance/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_attendance/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_cl/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_cl/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_si/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_si/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_event_questions/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_event_questions/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/crm_phone_validation/i18n/zh_CN.po -o //odoo/odoo-server/addons/crm_phone_validation/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_sparse_field/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_sparse_field/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pos_mercury/i18n/zh_CN.po -o //odoo/odoo-server/addons/pos_mercury/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_automation/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_automation/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pad/i18n/zh_CN.po -o //odoo/odoo-server/addons/pad/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/web_diagram/i18n/zh_CN.po -o //odoo/odoo-server/addons/web_diagram/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_iban/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_iban/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/theme_default/i18n/zh_CN.po -o //odoo/odoo-server/addons/theme_default/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_pa/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_pa/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_hr/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_hr/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/purchase_requisition/i18n/zh_CN.po -o //odoo/odoo-server/addons/purchase_requisition/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_adyen/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_adyen/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/fleet/i18n/zh_CN.po -o //odoo/odoo-server/addons/fleet/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_cr/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_cr/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_event/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_event/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_mx/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_mx/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_mail/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_mail/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_event_track/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_event_track/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/barcodes/i18n/zh_CN.po -o //odoo/odoo-server/addons/barcodes/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/google_calendar/i18n/zh_CN.po -o //odoo/odoo-server/addons/google_calendar/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_sa/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_sa/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_management/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_management/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/stock_picking_batch/i18n/zh_CN.po -o //odoo/odoo-server/addons/stock_picking_batch/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_payumoney/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_payumoney/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/decimal_precision/i18n/zh_CN.po -o //odoo/odoo-server/addons/decimal_precision/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/project/i18n/zh_CN.po -o //odoo/odoo-server/addons/project/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale_digital/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale_digital/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_setup/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_setup/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/stock/i18n/zh_CN.po -o //odoo/odoo-server/addons/stock/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_gamification/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_gamification/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_margin/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_margin/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/event/i18n/zh_CN.po -o //odoo/odoo-server/addons/event/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_address_extended/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_address_extended/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_maintenance/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_maintenance/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_gengo/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_gengo/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_timesheet_attendance/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_timesheet_attendance/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/link_tracker/i18n/zh_CN.po -o //odoo/odoo-server/addons/link_tracker/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_theme_install/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_theme_install/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_stripe/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_stripe/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/auth_signup/i18n/zh_CN.po -o //odoo/odoo-server/addons/auth_signup/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/purchase/i18n/zh_CN.po -o //odoo/odoo-server/addons/purchase/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_budget/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_budget/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/stock_dropshipping/i18n/zh_CN.po -o //odoo/odoo-server/addons/stock_dropshipping/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pos_data_drinks/i18n/zh_CN.po -o //odoo/odoo-server/addons/pos_data_drinks/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_crm_partner_assign/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_crm_partner_assign/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_contract/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_contract/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_expense/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_expense/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_tax_python/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_tax_python/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_co/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_co/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_paypal/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_paypal/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/association/i18n/zh_CN.po -o //odoo/odoo-server/addons/association/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/web_editor/i18n/zh_CN.po -o //odoo/odoo-server/addons/web_editor/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/document/i18n/zh_CN.po -o //odoo/odoo-server/addons/document/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_jp/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_jp/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/crm_livechat/i18n/zh_CN.po -o //odoo/odoo-server/addons/crm_livechat/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/event_sale/i18n/zh_CN.po -o //odoo/odoo-server/addons/event_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/note_pad/i18n/zh_CN.po -o //odoo/odoo-server/addons/note_pad/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pos_reprint/i18n/zh_CN.po -o //odoo/odoo-server/addons/pos_reprint/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_links/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_links/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/calendar_sms/i18n/zh_CN.po -o //odoo/odoo-server/addons/calendar_sms/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/purchase_mrp/i18n/zh_CN.po -o //odoo/odoo-server/addons/purchase_mrp/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_ro/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_ro/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_nl/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_nl/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_authorize/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_authorize/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale_comparison/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale_comparison/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale_delivery/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale_delivery/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_payment/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_payment/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/fetchmail/i18n/zh_CN.po -o //odoo/odoo-server/addons/fetchmail/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/transifex/i18n/zh_CN.po -o //odoo/odoo-server/addons/transifex/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/portal/i18n/zh_CN.po -o //odoo/odoo-server/addons/portal/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_ma/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_ma/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_rating/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_rating/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_check_printing/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_check_printing/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale_stock/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale_stock/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_org_chart/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_org_chart/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/stock_landed_costs/i18n/zh_CN.po -o //odoo/odoo-server/addons/stock_landed_costs/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/survey/i18n/zh_CN.po -o //odoo/odoo-server/addons/survey/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pos_sale/i18n/zh_CN.po -o //odoo/odoo-server/addons/pos_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/procurement_jit/i18n/zh_CN.po -o //odoo/odoo-server/addons/procurement_jit/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/web_tour/i18n/zh_CN.po -o //odoo/odoo-server/addons/web_tour/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_gengo/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_gengo/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_es/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_es/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/crm/i18n/zh_CN.po -o //odoo/odoo-server/addons/crm/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/phone_validation/i18n/zh_CN.po -o //odoo/odoo-server/addons/phone_validation/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/anonymization/i18n/zh_CN.po -o //odoo/odoo-server/addons/anonymization/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_recruitment_survey/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_recruitment_survey/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_be_intrastat/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_be_intrastat/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/rating/i18n/zh_CN.po -o //odoo/odoo-server/addons/rating/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_voucher/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_voucher/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale_options/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale_options/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_be_invoice_bba/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_be_invoice_bba/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/delivery/i18n/zh_CN.po -o //odoo/odoo-server/addons/delivery/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/product_margin/i18n/zh_CN.po -o //odoo/odoo-server/addons/product_margin/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pad_project/i18n/zh_CN.po -o //odoo/odoo-server/addons/pad_project/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/google_drive/i18n/zh_CN.po -o //odoo/odoo-server/addons/google_drive/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_pl/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_pl/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_ae/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_ae/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/crm_project/i18n/zh_CN.po -o //odoo/odoo-server/addons/crm_project/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pos_discount/i18n/zh_CN.po -o //odoo/odoo-server/addons/pos_discount/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_event_sale/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_event_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_recruitment/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_recruitment/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website/i18n/zh_CN.po -o //odoo/odoo-server/addons/website/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_mrp/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_mrp/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/analytic/i18n/zh_CN.po -o //odoo/odoo-server/addons/analytic/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pos_restaurant/i18n/zh_CN.po -o //odoo/odoo-server/addons/pos_restaurant/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/stock_account/i18n/zh_CN.po -o //odoo/odoo-server/addons/stock_account/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/resource/i18n/zh_CN.po -o //odoo/odoo-server/addons/resource/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/board/i18n/zh_CN.po -o //odoo/odoo-server/addons/board/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_hr/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_hr/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_uk/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_uk/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_twitter/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_twitter/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_payment/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_payment/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_do/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_do/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_timesheet/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_timesheet/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/web/i18n/zh_CN.po -o //odoo/odoo-server/addons/web/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_be_hr_payroll/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_be_hr_payroll/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_de/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_de/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/iap/i18n/zh_CN.po -o //odoo/odoo-server/addons/iap/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/product_email_template/i18n/zh_CN.po -o //odoo/odoo-server/addons/product_email_template/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/point_of_sale/i18n/zh_CN.po -o //odoo/odoo-server/addons/point_of_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_hn/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_hn/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_membership/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_membership/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hw_escpos/i18n/zh_CN.po -o //odoo/odoo-server/addons/hw_escpos/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_partner/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_partner/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/auth_oauth/i18n/zh_CN.po -o //odoo/odoo-server/addons/auth_oauth/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_payroll_account/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_payroll_account/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_mass_mailing/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_mass_mailing/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_vat/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_vat/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_mail_channel/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_mail_channel/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/membership/i18n/zh_CN.po -o //odoo/odoo-server/addons/membership/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/auth_ldap/i18n/zh_CN.po -o //odoo/odoo-server/addons/auth_ldap/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_holidays/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_holidays/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_asset/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_asset/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_be/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_be/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_import/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_import/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/calendar/i18n/zh_CN.po -o //odoo/odoo-server/addons/calendar/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_gr/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_gr/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/mass_mailing_event/i18n/zh_CN.po -o //odoo/odoo-server/addons/mass_mailing_event/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pos_cache/i18n/zh_CN.po -o //odoo/odoo-server/addons/pos_cache/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_bo/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_bo/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/web_settings_dashboard/i18n/zh_CN.po -o //odoo/odoo-server/addons/web_settings_dashboard/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/bus/i18n/zh_CN.po -o //odoo/odoo-server/addons/bus/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/gamification_sale_crm/i18n/zh_CN.po -o //odoo/odoo-server/addons/gamification_sale_crm/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_no/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_no/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_br/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_br/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_tr/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_tr/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_vn/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_vn/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_in/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_in/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_ogone/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_ogone/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/theme_bootswatch/i18n/zh_CN.po -o //odoo/odoo-server/addons/theme_bootswatch/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sms/i18n/zh_CN.po -o //odoo/odoo-server/addons/sms/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_fr/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_fr/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/product/i18n/zh_CN.po -o //odoo/odoo-server/addons/product/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/note/i18n/zh_CN.po -o //odoo/odoo-server/addons/note/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_pe/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_pe/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_ve/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_ve/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_ch/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_ch/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_sips/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_sips/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_buckaroo/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_buckaroo/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_blog/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_blog/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_pt/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_pt/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/odoo/addons/base/i18n/zh_CN.po -o //odoo/odoo-server/odoo/addons/base/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/custom/auto_backup/i18n/._zh_CN.po -o //odoo/custom/auto_backup/i18n/._zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/custom/auto_backup/i18n/zh_CN.po -o //odoo/custom/auto_backup/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/web_grid/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/web_grid/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/web_gantt/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/web_gantt/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/sale_subscription_asset/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/sale_subscription_asset/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/helpdesk_timesheet/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/helpdesk_timesheet/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_batch_deposit/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_batch_deposit/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/sale_ebay/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/sale_ebay/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/timesheet_grid_sale/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/timesheet_grid_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/delivery_usps/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/delivery_usps/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/event_barcode_mobile/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/event_barcode_mobile/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mrp_workorder/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mrp_workorder/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/marketing_automation/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/marketing_automation/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mass_mailing_themes/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mass_mailing_themes/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/delivery_dhl/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/delivery_dhl/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/delivery_bpost/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/delivery_bpost/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/sale_subscription/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/sale_subscription/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_taxcloud/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_taxcloud/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/project_forecast/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/project_forecast/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_helpdesk_livechat/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_helpdesk_livechat/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/stock_barcode_mobile/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/stock_barcode_mobile/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_sepa_direct_debit/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_sepa_direct_debit/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/sale_account_taxcloud/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/sale_account_taxcloud/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/project_timesheet_forecast_sale/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/project_timesheet_forecast_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/event_barcode/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/event_barcode/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/pos_loyalty/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/pos_loyalty/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_plaid/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_plaid/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_online_sync/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_online_sync/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_bank_statement_import_qif/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_bank_statement_import_qif/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/web_studio/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/web_studio/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/quality_mrp/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/quality_mrp/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_helpdesk_forum/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_helpdesk_forum/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_accountant/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_accountant/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_calendar/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_calendar/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/project_forecast_sale/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/project_forecast_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/web_enterprise/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/web_enterprise/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/delivery_fedex/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/delivery_fedex/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mrp_mps/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mrp_mps/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/web_mobile/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/web_mobile/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_sepa/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_sepa/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_sale_coupon/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_sale_coupon/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/voip_onsip/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/voip_onsip/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/voip/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/voip/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/currency_rate_live/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/currency_rate_live/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_version/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_version/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_bank_statement_import_csv/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_bank_statement_import_csv/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/project_timesheet_synchro/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/project_timesheet_synchro/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_sign/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_sign/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_crm_score/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_crm_score/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_helpdesk_form/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_helpdesk_form/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_studio/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_studio/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_enterprise/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_enterprise/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_helpdesk_slides/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_helpdesk_slides/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_helpdesk/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_helpdesk/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/helpdesk_sale_timesheet/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/helpdesk_sale_timesheet/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/delivery_barcode/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/delivery_barcode/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/hr_expense_sepa/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/hr_expense_sepa/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/delivery_ups/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/delivery_ups/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/base_automation_hr_contract/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/base_automation_hr_contract/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/print/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/print/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/hr_holidays_gantt/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/hr_holidays_gantt/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_delivery_ups/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_delivery_ups/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/l10n_be_coda/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/l10n_be_coda/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/sale_coupon_delivery/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/sale_coupon_delivery/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/hr_appraisal/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/hr_appraisal/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_sale_account_taxcloud/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_sale_account_taxcloud/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mrp_account/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mrp_account/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/l10n_us_check_printing/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/l10n_us_check_printing/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mrp_maintenance/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mrp_maintenance/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_reports_followup/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_reports_followup/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/hr_contract_salary/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/hr_contract_salary/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_form_editor/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_form_editor/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/stock_barcode/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/stock_barcode/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/website_quote_subscription/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/website_quote_subscription/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/inter_company_rules/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/inter_company_rules/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/helpdesk/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/helpdesk/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mail_push/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mail_push/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_deferred_revenue/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_deferred_revenue/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/l10n_be_reports/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/l10n_be_reports/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/timesheet_grid/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/timesheet_grid/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/sale_subscription_dashboard/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/sale_subscription_dashboard/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/print_sale/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/print_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_bank_statement_import_camt/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_bank_statement_import_camt/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_3way_match/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_3way_match/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mail_github/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mail_github/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_reports/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_reports/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_yodlee/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_yodlee/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/sale_coupon/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/sale_coupon/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/print_docsaway/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/print_docsaway/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/quality/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/quality/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/account_bank_statement_import_ofx/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/account_bank_statement_import_ofx/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/enterprise/mrp_plm/i18n/zh_CN.po -o //odoo/odoo-server/enterprise/mrp_plm/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_service_rating/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_service_rating/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_multilang/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_multilang/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/rating_project/i18n/zh_CN.po -o //odoo/odoo-server/addons/rating_project/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/utm/i18n/zh_CN.po -o //odoo/odoo-server/addons/utm/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/mass_mailing_event_track/i18n/zh_CN.po -o //odoo/odoo-server/addons/mass_mailing_event_track/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/mrp_repair/i18n/zh_CN.po -o //odoo/odoo-server/addons/mrp_repair/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_uy/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_uy/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/report_intrastat/i18n/zh_CN.po -o //odoo/odoo-server/addons/report_intrastat/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/maintenance/i18n/zh_CN.po -o //odoo/odoo-server/addons/maintenance/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/web_planner/i18n/zh_CN.po -o //odoo/odoo-server/addons/web_planner/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/im_livechat/i18n/zh_CN.po -o //odoo/odoo-server/addons/im_livechat/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_ar/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_ar/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_in_hr_payroll/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_in_hr_payroll/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_cancel/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_cancel/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/mrp_byproduct/i18n/zh_CN.po -o //odoo/odoo-server/addons/mrp_byproduct/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/web_kanban_gauge/i18n/zh_CN.po -o //odoo/odoo-server/addons/web_kanban_gauge/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale_management/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale_management/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_address_city/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_address_city/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account/i18n/zh_CN.po -o //odoo/odoo-server/addons/account/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_analytic_default/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_analytic_default/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sales_team/i18n/zh_CN.po -o //odoo/odoo-server/addons/sales_team/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_test/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_test/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_at/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_at/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/mail/i18n/zh_CN.po -o //odoo/odoo-server/addons/mail/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/google_account/i18n/zh_CN.po -o //odoo/odoo-server/addons/google_account/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_order_dates/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_order_dates/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_rating_project/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_rating_project/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_form/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_form/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_expense/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_expense/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_customer/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_customer/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_lu/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_lu/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_bank_statement_import/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_bank_statement_import/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_import_module/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_import_module/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/product_extended/i18n/zh_CN.po -o //odoo/odoo-server/addons/product_extended/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_sg/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_sg/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_livechat/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_livechat/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_syscohada/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_syscohada/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/lunch/i18n/zh_CN.po -o //odoo/odoo-server/addons/lunch/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_crm/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_crm/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_payment/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_payment/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_hr_recruitment/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_hr_recruitment/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_transfer/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_transfer/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_quote/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_quote/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_stock/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_stock/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_expense_check/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_expense_check/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_geolocalize/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_geolocalize/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/contacts/i18n/zh_CN.po -o //odoo/odoo-server/addons/contacts/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_crm/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_crm/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/product_expiry/i18n/zh_CN.po -o //odoo/odoo-server/addons/product_expiry/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_th/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_th/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/auth_crypt/i18n/zh_CN.po -o //odoo/odoo-server/addons/auth_crypt/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/mrp/i18n/zh_CN.po -o //odoo/odoo-server/addons/mrp/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/survey_crm/i18n/zh_CN.po -o //odoo/odoo-server/addons/survey_crm/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_payroll/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_payroll/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/gamification/i18n/zh_CN.po -o //odoo/odoo-server/addons/gamification/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale_wishlist/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale_wishlist/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_invoicing/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_invoicing/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_forum/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_forum/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_slides/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_slides/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/google_spreadsheet/i18n/zh_CN.po -o //odoo/odoo-server/addons/google_spreadsheet/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/project_timesheet_holidays/i18n/zh_CN.po -o //odoo/odoo-server/addons/project_timesheet_holidays/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_eu_service/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_eu_service/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_timesheet/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_timesheet/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_gt/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_gt/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_forum_doc/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_forum_doc/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_vat_autocomplete/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_vat_autocomplete/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/mass_mailing/i18n/zh_CN.po -o //odoo/odoo-server/addons/mass_mailing/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_attendance/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_attendance/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_cl/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_cl/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_si/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_si/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_event_questions/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_event_questions/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/crm_phone_validation/i18n/zh_CN.po -o //odoo/odoo-server/addons/crm_phone_validation/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_sparse_field/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_sparse_field/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pos_mercury/i18n/zh_CN.po -o //odoo/odoo-server/addons/pos_mercury/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_automation/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_automation/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pad/i18n/zh_CN.po -o //odoo/odoo-server/addons/pad/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/web_diagram/i18n/zh_CN.po -o //odoo/odoo-server/addons/web_diagram/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_iban/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_iban/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/theme_default/i18n/zh_CN.po -o //odoo/odoo-server/addons/theme_default/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_pa/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_pa/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_hr/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_hr/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/purchase_requisition/i18n/zh_CN.po -o //odoo/odoo-server/addons/purchase_requisition/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_adyen/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_adyen/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/fleet/i18n/zh_CN.po -o //odoo/odoo-server/addons/fleet/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_cr/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_cr/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_event/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_event/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_mx/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_mx/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_mail/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_mail/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_event_track/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_event_track/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/barcodes/i18n/zh_CN.po -o //odoo/odoo-server/addons/barcodes/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/google_calendar/i18n/zh_CN.po -o //odoo/odoo-server/addons/google_calendar/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_sa/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_sa/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_management/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_management/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/stock_picking_batch/i18n/zh_CN.po -o //odoo/odoo-server/addons/stock_picking_batch/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_payumoney/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_payumoney/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/decimal_precision/i18n/zh_CN.po -o //odoo/odoo-server/addons/decimal_precision/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/project/i18n/zh_CN.po -o //odoo/odoo-server/addons/project/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale_digital/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale_digital/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_setup/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_setup/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/stock/i18n/zh_CN.po -o //odoo/odoo-server/addons/stock/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_gamification/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_gamification/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_margin/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_margin/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/event/i18n/zh_CN.po -o //odoo/odoo-server/addons/event/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_address_extended/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_address_extended/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_maintenance/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_maintenance/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_gengo/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_gengo/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_timesheet_attendance/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_timesheet_attendance/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/link_tracker/i18n/zh_CN.po -o //odoo/odoo-server/addons/link_tracker/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_theme_install/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_theme_install/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_stripe/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_stripe/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/auth_signup/i18n/zh_CN.po -o //odoo/odoo-server/addons/auth_signup/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/purchase/i18n/zh_CN.po -o //odoo/odoo-server/addons/purchase/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_budget/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_budget/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/stock_dropshipping/i18n/zh_CN.po -o //odoo/odoo-server/addons/stock_dropshipping/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pos_data_drinks/i18n/zh_CN.po -o //odoo/odoo-server/addons/pos_data_drinks/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_crm_partner_assign/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_crm_partner_assign/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_contract/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_contract/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_expense/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_expense/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_tax_python/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_tax_python/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_co/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_co/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_paypal/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_paypal/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/association/i18n/zh_CN.po -o //odoo/odoo-server/addons/association/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/web_editor/i18n/zh_CN.po -o //odoo/odoo-server/addons/web_editor/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/document/i18n/zh_CN.po -o //odoo/odoo-server/addons/document/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_jp/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_jp/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/crm_livechat/i18n/zh_CN.po -o //odoo/odoo-server/addons/crm_livechat/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/event_sale/i18n/zh_CN.po -o //odoo/odoo-server/addons/event_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/note_pad/i18n/zh_CN.po -o //odoo/odoo-server/addons/note_pad/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pos_reprint/i18n/zh_CN.po -o //odoo/odoo-server/addons/pos_reprint/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_links/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_links/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/calendar_sms/i18n/zh_CN.po -o //odoo/odoo-server/addons/calendar_sms/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/purchase_mrp/i18n/zh_CN.po -o //odoo/odoo-server/addons/purchase_mrp/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_ro/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_ro/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_nl/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_nl/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_authorize/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_authorize/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale_comparison/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale_comparison/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale_delivery/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale_delivery/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_payment/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_payment/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/fetchmail/i18n/zh_CN.po -o //odoo/odoo-server/addons/fetchmail/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/transifex/i18n/zh_CN.po -o //odoo/odoo-server/addons/transifex/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/portal/i18n/zh_CN.po -o //odoo/odoo-server/addons/portal/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_ma/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_ma/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_rating/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_rating/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_check_printing/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_check_printing/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale_stock/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale_stock/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_org_chart/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_org_chart/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/stock_landed_costs/i18n/zh_CN.po -o //odoo/odoo-server/addons/stock_landed_costs/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/survey/i18n/zh_CN.po -o //odoo/odoo-server/addons/survey/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pos_sale/i18n/zh_CN.po -o //odoo/odoo-server/addons/pos_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/procurement_jit/i18n/zh_CN.po -o //odoo/odoo-server/addons/procurement_jit/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/web_tour/i18n/zh_CN.po -o //odoo/odoo-server/addons/web_tour/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_gengo/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_gengo/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_es/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_es/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/crm/i18n/zh_CN.po -o //odoo/odoo-server/addons/crm/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/phone_validation/i18n/zh_CN.po -o //odoo/odoo-server/addons/phone_validation/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/anonymization/i18n/zh_CN.po -o //odoo/odoo-server/addons/anonymization/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_recruitment_survey/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_recruitment_survey/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_be_intrastat/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_be_intrastat/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/rating/i18n/zh_CN.po -o //odoo/odoo-server/addons/rating/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_voucher/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_voucher/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale_options/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale_options/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_be_invoice_bba/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_be_invoice_bba/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/delivery/i18n/zh_CN.po -o //odoo/odoo-server/addons/delivery/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/product_margin/i18n/zh_CN.po -o //odoo/odoo-server/addons/product_margin/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pad_project/i18n/zh_CN.po -o //odoo/odoo-server/addons/pad_project/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/google_drive/i18n/zh_CN.po -o //odoo/odoo-server/addons/google_drive/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_pl/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_pl/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_ae/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_ae/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/crm_project/i18n/zh_CN.po -o //odoo/odoo-server/addons/crm_project/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pos_discount/i18n/zh_CN.po -o //odoo/odoo-server/addons/pos_discount/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_event_sale/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_event_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_recruitment/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_recruitment/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website/i18n/zh_CN.po -o //odoo/odoo-server/addons/website/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale_mrp/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale_mrp/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/analytic/i18n/zh_CN.po -o //odoo/odoo-server/addons/analytic/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pos_restaurant/i18n/zh_CN.po -o //odoo/odoo-server/addons/pos_restaurant/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/stock_account/i18n/zh_CN.po -o //odoo/odoo-server/addons/stock_account/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/resource/i18n/zh_CN.po -o //odoo/odoo-server/addons/resource/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/board/i18n/zh_CN.po -o //odoo/odoo-server/addons/board/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_hr/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_hr/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_uk/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_uk/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_twitter/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_twitter/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_payment/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_payment/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_do/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_do/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_timesheet/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_timesheet/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/web/i18n/zh_CN.po -o //odoo/odoo-server/addons/web/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_be_hr_payroll/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_be_hr_payroll/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_de/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_de/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/iap/i18n/zh_CN.po -o //odoo/odoo-server/addons/iap/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/product_email_template/i18n/zh_CN.po -o //odoo/odoo-server/addons/product_email_template/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/point_of_sale/i18n/zh_CN.po -o //odoo/odoo-server/addons/point_of_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_hn/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_hn/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_membership/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_membership/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hw_escpos/i18n/zh_CN.po -o //odoo/odoo-server/addons/hw_escpos/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_partner/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_partner/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/auth_oauth/i18n/zh_CN.po -o //odoo/odoo-server/addons/auth_oauth/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_payroll_account/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_payroll_account/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_mass_mailing/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_mass_mailing/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_vat/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_vat/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_mail_channel/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_mail_channel/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_sale/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/membership/i18n/zh_CN.po -o //odoo/odoo-server/addons/membership/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/auth_ldap/i18n/zh_CN.po -o //odoo/odoo-server/addons/auth_ldap/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/hr_holidays/i18n/zh_CN.po -o //odoo/odoo-server/addons/hr_holidays/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/account_asset/i18n/zh_CN.po -o //odoo/odoo-server/addons/account_asset/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_be/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_be/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/base_import/i18n/zh_CN.po -o //odoo/odoo-server/addons/base_import/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/calendar/i18n/zh_CN.po -o //odoo/odoo-server/addons/calendar/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_gr/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_gr/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/mass_mailing_event/i18n/zh_CN.po -o //odoo/odoo-server/addons/mass_mailing_event/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/pos_cache/i18n/zh_CN.po -o //odoo/odoo-server/addons/pos_cache/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_bo/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_bo/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/web_settings_dashboard/i18n/zh_CN.po -o //odoo/odoo-server/addons/web_settings_dashboard/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/bus/i18n/zh_CN.po -o //odoo/odoo-server/addons/bus/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/gamification_sale_crm/i18n/zh_CN.po -o //odoo/odoo-server/addons/gamification_sale_crm/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_no/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_no/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_br/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_br/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_tr/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_tr/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_vn/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_vn/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_in/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_in/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_ogone/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_ogone/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/theme_bootswatch/i18n/zh_CN.po -o //odoo/odoo-server/addons/theme_bootswatch/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sms/i18n/zh_CN.po -o //odoo/odoo-server/addons/sms/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_fr/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_fr/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/product/i18n/zh_CN.po -o //odoo/odoo-server/addons/product/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/note/i18n/zh_CN.po -o //odoo/odoo-server/addons/note/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_pe/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_pe/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_ve/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_ve/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/sale/i18n/zh_CN.po -o //odoo/odoo-server/addons/sale/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_ch/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_ch/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_sips/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_sips/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/payment_buckaroo/i18n/zh_CN.po -o //odoo/odoo-server/addons/payment_buckaroo/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/website_blog/i18n/zh_CN.po -o //odoo/odoo-server/addons/website_blog/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/addons/l10n_pt/i18n/zh_CN.po -o //odoo/odoo-server/addons/l10n_pt/i18n/zh_TW.po 
sudo cconv -f UTF8-CN -t UTF8-HK //odoo/odoo-server/odoo/addons/base/i18n/zh_CN.po -o //odoo/odoo-server/odoo/addons/base/i18n/zh_TW.po 
